<?php

namespace Ath\ExerciseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExerciseFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExerciseFileRepository extends EntityRepository
{
}
