<?php

namespace Ath\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfessorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessorRepository extends EntityRepository
{
	public function getProfessorsByClasseId($id)
	{
		$qb = $this->createQueryBuilder('p')
		->join('p.classes', 'c','WITH','c.id = :id')
		->setParameter('id',$id);
	
		return $qb->getQuery()
		->getResult();
	}
}
