<?php

namespace Ath\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CourseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends EntityRepository
{
// 	public function findByDiscipline($matiere){
// 		return $this->getEntityManager()
// 		->createQuery(
// 				'SELECT c FROM AthCoursBundle:cours c WHERE c.matiere = :matiere'
// 		)
// 		->setParameter('id', $id)
// 		->getResult();
// 	}
}
