<?php

namespace Ath\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DisciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplineRepository extends EntityRepository
{
	/*public function getDisciplinesByClasseId($id)
	{
		$qb = $this->createQueryBuilder('d')
		->join('d.classes', 'c','WITH','c.id = :id')
		->setParameter('id',$id);

		return $qb->getQuery()
		->getResult();
	}*/
}
