<?php

namespace Ath\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DisciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplineRepository extends EntityRepository
{

  // retourne les matières qui n'ont pas de prof, pour une classe donnée
	public function getDisciplinesWithoutTeacher(\Ath\UserBundle\Entity\Classe $classe){
    $query = $this->_em->createQuery("SELECT d FROM Ath\CoursBundle\Entity\Discipline d WHERE d NOT IN (
                              SELECT discipline FROM Ath\CoursBundle\Entity\Teaching teaching JOIN teaching.discipline discipline WHERE teaching.classe = ?1
                              )");
    $query->setParameter(1, $classe);
    return $query->getResult();
  }
}
