<?php

namespace Ath\CoursBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeachingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeachingRepository extends EntityRepository
{
}
